// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcW8FJHTF9VLirkvtR8BaGoZMiOfCtl3M',
    appId: '1:791210247900:web:2f7d3ae59bb9e1682e5619',
    messagingSenderId: '791210247900',
    projectId: 'field-zoom',
    authDomain: 'field-zoom.firebaseapp.com',
    storageBucket: 'field-zoom.appspot.com',
    measurementId: 'G-4788RF6ZE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7a3vlcFGOAi_rl1be0dhkcyi9jghwsDQ',
    appId: '1:791210247900:android:fb3e96e20b37306c2e5619',
    messagingSenderId: '791210247900',
    projectId: 'field-zoom',
    storageBucket: 'field-zoom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYXCSxBYzWPQa3zmjil0fYLLl-DNJTss',
    appId: '1:791210247900:ios:f5c5359c2534c1932e5619',
    messagingSenderId: '791210247900',
    projectId: 'field-zoom',
    storageBucket: 'field-zoom.appspot.com',
    androidClientId: '791210247900-oi4qd052cnv6kfpps3jch2h367669a92.apps.googleusercontent.com',
    iosClientId: '791210247900-3rg0g7q38cmebtm982ahk2hl6fvj2043.apps.googleusercontent.com',
    iosBundleId: 'simonsayz.pro.fieldZoomProWeb',
  );
}
